.TH topologic-glut 1 "OCTOBER 2013" TOPOLOGIC "Application Manuals"

.SH NAME
topologic \- GLUT frontend for topologic

.SH SYNOPSIS
.B topologic-glut [
.I options ...
.B ] [
.I files ...
.B ]

.SH DESCRIPTION
.B topologic-glut
is a programme that renders higher dimensional variants of basic geometric
primitives in OpenGL. In essence it's a GLUT-based frontend to
.BR topologic (1)

Please refer to the man page of
.BR topologic (1)
for a description of the command line parameters and example invocations.

.SH AUTHOR
Magnus Deininger <magnus@ef.gy>

.SH "SEE ALSO"
.BR topologic (1)
